### TIER 0 NODES ###
[tier0]
; digitafrica-edge-node1 ansible_host=10.64.45.176 ansible_ssh_pass="1234" ansible_become_pass="1234" tier0_k3s_mode="none"
; digitafrica-edge-node1 ansible_host=10.64.45.176 ansible_ssh_pass="1234" ansible_become_pass="1234" tier0_k3s_mode="single"

### TIER 1 NODES ###
[tier1_server]
digitafrica-edge-node1 ansible_host=172.28.2.119

[tier1_agents]
digitafrica-edge-node2 ansible_host=172.28.2.105

[tier1:children]
tier1_server
tier1_agents

[all:vars]
ansible_user=bdyshlev
ansible_become=true
ansible_ssh_common_args='-o ProxyJump=proxy@bastion1.theblueprintfactory.org'
